-- Journal des échecs de génération, une fois toutes les tentatives client
-- épuisées (voir callAI, js/api.js). Alimente la carte "Échecs de
-- génération" du Tableau de bord (voir carteErreursAdmin, js/admin.js).
-- À exécuter une fois dans l'éditeur SQL de Supabase. Tant que cette table
-- n'existe pas, l'app continue de fonctionner normalement : l'écriture
-- (resource=erreur, api/data.js) comme la lecture (admin-stats) échouent
-- silencieusement, la carte reste simplement absente du tableau de bord.
create table if not exists erreurs_generation (
  id         bigint generated by default as identity primary key,
  mode       text,
  code_acces text,
  detail     text,
  cree_le    timestamptz not null default now()
);

-- Verrouillée comme generations/series/abonnes (voir
-- generations_series_rls.sql, abonnes_rls.sql) : journal opérationnel par
-- code d'accès, aucune raison de l'exposer au rôle anon. Seul le serveur
-- (clé service_role, contourne RLS) y écrit et la lit ; aucune policy
-- créée ici = accès refusé par défaut à anon.
alter table erreurs_generation enable row level security;
