-- Journal des vidéos réellement montées, une ligne par rendu réussi.
--
-- Pourquoi cette table : le montage vidéo vient d'être ouvert aux abonnés
-- Creator et Pro (il était réservé au fondateur le temps d'en mesurer le
-- coût). Le quota d'IMAGES est déjà compté (usage_serveur, montageImages),
-- mais le rendu lui-même ne l'était nulle part : impossible de savoir
-- combien de vidéos sortent réellement de l'app, ni qui s'en sert.
--
-- Ce qu'on enregistre, et pourquoi chaque colonne mérite sa place :
--   - le PLAN, pour voir si le montage pousse vraiment à l'abonnement Pro
--     ou s'il reste un usage Creator ;
--   - le nombre de plans et la durée de la vidéo, parce que c'est ce qui
--     détermine le coût de calcul (voir le chronométrage du service de
--     rendu, render-service/server.js) ;
--   - la durée du rendu, mesurée côté serveur, pour suivre dans le temps si
--     ça se dégrade quand plusieurs abonnés montent en même temps ;
--   - les options réellement utilisées (sous-titres, musique, filigrane),
--     pour savoir lesquelles gagnent leur complexité.
--
-- Aucune donnée de contenu : ni texte, ni images, ni URL de la vidéo. Rien
-- qui permette de relire ce qu'un créateur a monté, uniquement des mesures.
--
-- À exécuter une fois dans l'éditeur SQL de Supabase. Tant que cette table
-- n'existe pas, l'app fonctionne normalement : l'écriture
-- (api/montage-render.js) comme la lecture (admin-stats, api/data.js)
-- échouent silencieusement, la carte reste simplement absente du Tableau de
-- bord. Un rendu vidéo ne doit JAMAIS échouer parce que sa mesure a échoué.
create table if not exists montages_rendus (
  id             bigint generated by default as identity primary key,
  code_acces     text,
  plan           text,        -- 'creator', 'pro', ou 'fondateur'
  nb_plans       int,         -- nombre d'images assemblées
  duree_video_s  numeric,     -- durée de la vidéo produite, en secondes
  duree_rendu_ms int,         -- temps de rendu mesuré côté serveur
  format         text,        -- '9:16', '1:1', '16:9'
  sous_titres    boolean,
  musique        boolean,
  filigrane      boolean,
  cree_le        timestamptz not null default now()
);

-- Verrouillée comme erreurs_generation et passes_generation : donnée
-- opérationnelle interne, aucune raison de l'exposer au rôle anon. Seul le
-- serveur (clé service_role, qui contourne RLS) y écrit et la lit ; aucune
-- policy créée ici = accès refusé par défaut à anon.
alter table montages_rendus enable row level security;
