-- Vidéos montées actuellement disponibles à récupérer depuis « Mes
-- générations » (retour propriétaire, 27/09) : jusqu'ici, une vidéo rendue
-- puis jamais téléchargée dans la même session était perdue - le fichier
-- restait dans le Storage (voir montage_storage.sql) mais son URL n'était
-- gardée nulle part, seul le navigateur du créateur la connaissait un
-- instant. Fermer l'onglet avant de cliquer sur « Télécharger » la rendait
-- introuvable pour toujours, même si le fichier existait encore.
--
-- Une ligne = une vidéo actuellement récupérable. SUPPRIMÉE (jamais juste
-- marquée) dès qu'elle n'a plus lieu d'être listée :
--   - téléchargée (voir api/montage-media.js, action=confirmer-telechargement,
--     qui supprime la ligne EN MÊME TEMPS que le fichier du Storage) ;
--   - expirée à 3 jours (voir api/cron-nettoyage-montages.js, purge
--     quotidienne), même si jamais téléchargée.
-- Aucune raison de garder une ligne qui pointe vers un fichier qui n'existe
-- plus : ni un badge « déjà téléchargée », ni un historique permanent n'ont
-- été demandés, seulement de pouvoir la retrouver avant qu'elle disparaisse.
--
-- Distincte de `montages_rendus` (mesures agrégées, sans aucune donnée de
-- contenu, voir ce fichier) : celle-ci porte volontairement l'URL, exactement
-- pour permettre de la retrouver depuis un autre appareil ou plus tard dans
-- la journée.
--
-- À exécuter une fois dans l'éditeur SQL de Supabase. Tant que cette table
-- n'existe pas, l'app fonctionne normalement : l'écriture
-- (api/montage-render.js) comme la lecture (api/data.js, resource
-- montages-video) échouent silencieusement, la section reste simplement
-- absente de « Mes générations ». Un rendu vidéo ne doit JAMAIS échouer
-- parce que cet enregistrement a échoué.
create table if not exists montages_video (
  id         bigint generated by default as identity primary key,
  code_acces text not null,
  url        text not null,
  format     text,        -- '9:16', '1:1', '16:9', informatif seulement
  cree_le    timestamptz not null default now()
);

create index if not exists montages_video_code_acces_idx on montages_video (code_acces);
create index if not exists montages_video_cree_le_idx on montages_video (cree_le);

-- Même principe que montages_rendus/generations : donnée qui identifie un
-- abonné et pointe vers son contenu, aucune raison de l'exposer au rôle
-- anon. Seul le serveur (clé service_role, qui contourne RLS) y écrit et la
-- lit ; aucune policy créée ici = accès refusé par défaut à anon.
alter table montages_video enable row level security;
