-- Mesure des passes de perfectionnement du pipeline (Script et Récit), une
-- ligne par génération réussie. Sert à répondre par des CHIFFRES, et non à
-- l'intuition, à la question posée par le propriétaire : est-ce que la boucle
-- de correction de durée et la boucle qualité (Critique + Réviseur) gagnent
-- vraiment leur coût en jetons et en temps d'attente ?
--
-- Chaque passe mesurée ici est un appel IA complet qui renvoie le texte entier
-- dans le prompt et le fait réécrire : c'est le vrai poids du pipeline, bien
-- plus que le plafond de jetons de chaque appel (un plafond est réservé, pas
-- facturé). Si la correction de durée ne se déclenche presque jamais, ou si le
-- Critique valide le premier jet dans 90% des cas, on saura quoi alléger sans
-- rien casser. Sinon on saura que ces passes sont utiles, et on arrêtera de se
-- poser la question.
--
-- Aucune donnée de contenu n'est enregistrée : ni le sujet, ni le texte, ni le
-- script. Uniquement des compteurs.
--
-- À exécuter une fois dans l'éditeur SQL de Supabase. Tant que cette table
-- n'existe pas, l'app fonctionne normalement : l'écriture (resource=passes,
-- api/data.js) comme la lecture (admin-stats) échouent silencieusement, la
-- carte reste simplement absente du Tableau de bord.
create table if not exists passes_generation (
  id                bigint generated by default as identity primary key,
  mode              text,        -- 'script' ou 'story'
  code_acces        text,
  duree_cible       text,        -- ex. '2 minutes', vide en récit long
  mots_final        int,         -- compte de mots réellement livré
  dans_cible        boolean,     -- le script/récit final tient-il la durée choisie
  corrections_duree int,         -- tours réellement effectués par la boucle de durée (0 = jamais déclenchée)
  critiques         int,         -- nombre d'appels au Critique
  revisions         int,         -- nombre de réécritures ciblées par le Réviseur
  second_brouillon  boolean,     -- une réécriture complète a-t-elle été relancée
  cree_le           timestamptz not null default now()
);

-- Verrouillée comme erreurs_generation (voir erreurs_generation.sql) : donnée
-- opérationnelle interne, aucune raison de l'exposer au rôle anon. Seul le
-- serveur (clé service_role, contourne RLS) y écrit et la lit ; aucune policy
-- créée ici = accès refusé par défaut à anon.
alter table passes_generation enable row level security;
